from __future__ import annotations

import argparse
import sys
from importlib import resources
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined


START_MARKER = "<!-- agents-md-templates:start -->"
END_MARKER = "<!-- agents-md-templates:end -->"
TEMPLATE_SUFFIX = ".md"
BASE_TEMPLATE = "base"
COMMAND_NAME = "create-agents-md"
TEMPLATE_HIERARCHY = (
    ("general", (BASE_TEMPLATE,)),
    ("ecosystem", ("python", "nextjs")),
    ("domain", ("deep-learning",)),
    ("framework", ("jax-equinox", "pytorch")),
)
TEMPLATE_ORDER = {
    name: (level, position)
    for level, (_category, names) in enumerate(TEMPLATE_HIERARCHY)
    for position, name in enumerate(names)
}


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=COMMAND_NAME,
        description="Generate and update AGENTS.md files from bundled templates.",
    )
    parser.add_argument(
        "--target",
        type=Path,
        default=Path.cwd(),
        help="project directory or AGENTS.md path to write (default: current directory)",
    )
    parser.add_argument(
        "--template",
        action="append",
        choices=template_names(),
        help="template to include; repeat for multiple templates (skips the prompt)",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="replace the entire AGENTS.md file instead of updating the managed block",
    )
    parser.set_defaults(func=write_command)

    subparsers = parser.add_subparsers(dest="command")

    list_parser = subparsers.add_parser("list", help="list bundled templates")
    list_parser.set_defaults(func=list_command)

    return parser


def list_command(_args: argparse.Namespace) -> int:
    for name in template_names():
        print(name)
    return 0


def write_command(args: argparse.Namespace) -> int:
    target = args.target.resolve()
    output_path = target if target.name == "AGENTS.md" else target / "AGENTS.md"
    project_dir = output_path.parent

    selected = select_templates(explicit=args.template)
    generated = render_managed_block(
        selected,
        context={
            "output_path": str(output_path),
            "project_dir": str(project_dir),
            "selected_templates": selected,
        },
    )

    if args.replace:
        next_content = generated + "\n"
    else:
        current = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        next_content = upsert_managed_block(current, generated)

    print(next_content, end="")
    sys.stdout.flush()

    project_dir.mkdir(parents=True, exist_ok=True)
    output_path.write_text(next_content, encoding="utf-8")
    print(f"\nWrote {output_path} with templates: {', '.join(selected)}", file=sys.stderr)
    return 0


def select_templates(*, explicit: list[str] | None) -> list[str]:
    selected: list[str] = []

    def add(name: str) -> None:
        if name not in selected:
            selected.append(name)

    if explicit:
        for name in explicit:
            add(name)

    if not explicit:
        selected = prompt_for_templates()

    if not selected:
        add(BASE_TEMPLATE)

    return order_templates(selected)


def prompt_for_templates() -> list[str]:
    selected: list[str] = []

    print("Select templates to include in AGENTS.md:", file=sys.stderr)
    for name in template_names():
        default = name == BASE_TEMPLATE
        if confirm(f"Include {name}?", default=default):
            selected.append(name)

    return selected


def confirm(prompt: str, *, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "

    while True:
        print(prompt + suffix, end="", file=sys.stderr, flush=True)
        answer = sys.stdin.readline().strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("Please answer y or n.", file=sys.stderr)


def render_managed_block(selected: list[str], *, context: dict[str, object]) -> str:
    selected = order_templates(selected)
    context = {**context, "selected_templates": selected}
    chunks = [
        START_MARKER,
        f"<!-- Generated by `{COMMAND_NAME}`; edit templates or content outside this block. -->",
    ]
    chunks.extend(render_template(name, context=context) for name in selected)
    chunks.append(END_MARKER)
    return "\n\n".join(chunks).strip()


def render_template(name: str, *, context: dict[str, object]) -> str:
    template = template_environment().get_template(template_filename(name))
    return template.render({**context, "template_name": name}).strip()


def upsert_managed_block(current: str, generated: str) -> str:
    current = current.rstrip()
    start = current.find(START_MARKER)
    end = current.find(END_MARKER)

    if start != -1 and end != -1 and start < end:
        end += len(END_MARKER)
        return f"{current[:start].rstrip()}\n\n{generated}\n\n{current[end:].lstrip()}".strip() + "\n"

    if not current:
        return generated + "\n"

    return f"{current}\n\n{generated}\n"


def template_names() -> list[str]:
    names: list[str] = []
    for path in templates_dir().iterdir():
        if path.is_file() and path.name.endswith(TEMPLATE_SUFFIX):
            names.append(path.name.removesuffix(TEMPLATE_SUFFIX))
    return order_templates(names)


def order_templates(names: list[str]) -> list[str]:
    return sorted(names, key=template_sort_key)


def template_sort_key(name: str) -> tuple[int, int, str]:
    level, position = TEMPLATE_ORDER.get(name, (len(TEMPLATE_HIERARCHY), 0))
    return (level, position, name)


def template_filename(name: str) -> str:
    return f"{name}{TEMPLATE_SUFFIX}"


def template_environment() -> Environment:
    return Environment(
        loader=FileSystemLoader(templates_dir()),
        autoescape=False,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


def templates_dir() -> Path:
    return Path(str(resources.files("agents_md_templates") / "templates"))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
